name: Release # stub from https://github.com/softprops/action-gh-release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build .

      - name: Compile
        run: |
          mkdir build \
          && docker run \
            -v ./build:/root/scheme-langserver/build/ \
            $(docker build -q .) \
            bash -c 'source .akku/bin/activate
                     compile-chez-program run.ss
                     mv run buil/run || exit 1
                     echo Build Success
                     '

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repo: konst-aa/scheme-langserver
          files: run

